import { AttendanceProcedure } from "@/src/types/attendance_procedure";
import { ColumnDefinition } from "./patient";

export const ATTENDANCE_PROCEDURE_COLUMNS: ColumnDefinition<AttendanceProcedure>[] = [
  {
    name: "procedure_id",
    label: "Procedure",
    type: "search_input",
    width: "100",
    required: true,
    grid: true,
    form: true,
    details: true,
    render: (item) => item.procedure?.name || "—",
  },
  {
    name: "start_time",
    label: "Start Time",
    type: "date",
    width: "50",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.start_time ? new Date(item.start_time).toLocaleString() : "—",
  },
  {
    name: "end_time",
    label: "End Time",
    type: "date",
    width: "50",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.end_time ? new Date(item.end_time).toLocaleString() : "—",
  },
  {
    name: "ordered_by_id",
    label: "Ordered By",
    type: "search_input",
    width: "50",
    grid: false,
    form: true,
    details: true,
    render: (item) => item.ordered_by?.full_name || "—",
  },
  {
    name: "executed_by_id",
    label: "Executed By",
    type: "search_input",
    width: "50",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.executed_by?.full_name || "—",
  },
  {
    name: "medications",
    label: "Medications",
    type: "multi_search_input",
    width: "100",
    grid: true,
    form: true,
    details: true,
    render: (item) => item.medications?.map(m => m.trade_name).join(", ") || "—",
  },
];
