import { Sex } from "@/src/types/patient";
import { EmploymentType, Employee } from "@/src/types/employee";
import { ColumnDefinition } from "./patient";

export const EMPLOYEE_COLUMNS: ColumnDefinition<Employee>[] = [
  {
    name: "full_name",
    label: "Full Name",
    type: "text",
    width: "100",
    required: true,
    placeholder: "Enter full name",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "social_name",
    label: "Social Name",
    type: "text",
    width: "100",
    placeholder: "Enter social name (optional)",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "cpf",
    label: "CPF",
    type: "text",
    width: "50",
    required: true,
    placeholder: "000.000.000-00",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "rg",
    label: "RG",
    type: "text",
    width: "50",
    placeholder: "Enter RG",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "birth_date",
    label: "Birth Date",
    type: "date",
    width: "50",
    required: true,
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "sex",
    label: "Sex",
    type: "select",
    width: "50",
    options: [
      { label: "Male", value: Sex.MALE },
      { label: "Female", value: Sex.FEMALE },
      { label: "Other", value: Sex.OTHER },
    ],
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "marital_status",
    label: "Marital Status",
    type: "text",
    width: "50",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "nationality",
    label: "Nationality",
    type: "text",
    width: "50",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "phone",
    label: "Phone",
    type: "tel",
    width: "50",
    placeholder: "(00) 00000-0000",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "hire_date",
    label: "Hire Date",
    type: "date",
    width: "50",
    required: true,
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "termination_date",
    label: "Termination Date",
    type: "date",
    width: "50",
    grid: false,
    form: true,
    details: true,
  },
  {
    name: "employment_type",
    label: "Employment Type",
    type: "select",
    width: "50",
    options: Object.values(EmploymentType).map((type) => ({ label: type, value: type })),
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "salary",
    label: "Salary",
    type: "text",
    width: "50",
    placeholder: "0.00",
    grid: true,
    form: true,
    details: true,
  },
  {
    name: "active",
    label: "Active",
    type: "select",
    width: "50",
    options: [
      { label: "Yes", value: true as any },
      { label: "No", value: false as any },
    ],
    grid: true,
    form: true,
    details: true,
    badge: true,
  },
  {
    name: "role",
    label: "Role",
    type: "text",
    grid: true,
    form: false,
    details: true,
    render: (employee: Employee) => employee.role?.name || "—",
  },
  {
    name: "role_id",
    label: "Role",
    type: "select",
    width: "50",
    required: true,
    grid: false,
    form: true,
    details: false,
  },
];
