"""removing_dosage_prescription

Revision ID: 2d86b8d15a58
Revises: c840b84a69b0
Create Date: 2026-05-25 18:48:33.696867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d86b8d15a58'
down_revision = 'c840b84a69b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'dosage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('dosage', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
