"""remove_medical_record_number_from_patient

Revision ID: 35db7a18e3b1
Revises: eb6451ae9a1a
Create Date: 2026-05-24 00:12:35.876682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35db7a18e3b1'
down_revision = 'eb6451ae9a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patients_medical_record_number_key'), 'patients', type_='unique')
    op.drop_column('patients', 'medical_record_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('medical_record_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('patients_medical_record_number_key'), 'patients', ['medical_record_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
