"""adding_attendance_prescription_columns

Revision ID: c840b84a69b0
Revises: 374a58599a3e
Create Date: 2026-05-25 18:43:51.947658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c840b84a69b0'
down_revision = '374a58599a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('Waiting Triage', 'Waiting Consultation', 'Waiting Medication', 'Medical Return', 'Finished', 'Cancelled', name='attendancestatus'), server_default='Waiting Triage', nullable=False),
    sa.Column('triage_notes', sa.Text(), nullable=True),
    sa.Column('vitals_bp', sa.String(length=20), nullable=True),
    sa.Column('vitals_temp', sa.String(length=10), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attendance_id', sa.BigInteger(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=False),
    sa.Column('is_executed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
